#!/usr/bin/env python3
"""One-shot Musia internal release; offline planning unless explicitly requested.

Plan: --build-receipt BUILD --qa QA (no credentials, API calls, or writes).
Execute: add --execute --service-account-file KEY --coordination-file HANDOFF.
Reconcile: --readback OPERATION --service-account-file KEY --coordination-file HANDOFF.
Readback never uploads, updates a track, commits, or authorizes another execution.
It observes an open original edit, or creates/deletes a fresh read edit after a
commit attempt. These observations are not proof of tester availability/review.

HANDOFF is an owner-only JSON receipt from the parent, not generated by this tool:
schema=1, bundle_id=art.lazying.musia, track=internal, version_code (string),
artifact_sha256, parent_session, checked_at (timezone-aware ISO timestamp), and
ui_quiescent, no_other_edits, no_pending_changes, no_changes_in_review,
commit_invalidates_edits_ack all true. The parent must reserve the app against
Console/API writers for this operation. The receipt expires after ten minutes
and is checked before EVERY mutation. Track APIs cannot prove absence of Console
drafts or other users' edits; this live coordination is a separate prerequisite.

Protocol references:
https://developers.google.com/android-publisher/api-ref/rest/v3/edits.bundles/upload
https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks/update
https://developers.google.com/android-publisher/api-ref/rest/v3/edits/commit
"""
from __future__ import annotations

import argparse
import copy
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
import re
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from musia.creator.billing_providers import GoogleVerifier
import storelib as s

PACKAGE = "art.lazying.musia"
TRACK = "internal"
BASE = "https://androidpublisher.googleapis.com/androidpublisher/v3/applications/" + PACKAGE
UPLOAD_BASE = "https://androidpublisher.googleapis.com/upload/androidpublisher/v3/applications/" + PACKAGE
COMMIT_QUERY = "?changesNotSentForReview=true&changesInReviewBehavior=ERROR_IF_IN_REVIEW"
COORDINATION_FLAGS = ("ui_quiescent", "no_other_edits", "no_pending_changes",
                      "no_changes_in_review", "commit_invalidates_edits_ack")


def version_code(value):
    s.require(type(value) in (str, int) and re.fullmatch(r"[1-9][0-9]{0,9}", str(value))
              and int(value) <= 2100000000, "Invalid Android version code")
    return str(value)


def sha256(value):
    s.require(isinstance(value, str) and re.fullmatch(r"[0-9a-f]{64}", value), "Invalid SHA256")
    return value


def edit_id(value):
    s.require(isinstance(value, str) and re.fullmatch(r"[A-Za-z0-9_-]{1,200}", value),
              "Invalid provider edit ID")
    return value


def operation_path(code):
    # Version, not caller-chosen operation name/hash: rebuilding cannot bypass it.
    return s.RUNTIME / "operations" / ("play-internal-api-" + version_code(code) + ".json")


def save(path, value):
    s.write_private(path, value)
    fd = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def qualified(build_receipt, qa):
    s.require(build_receipt is not None and qa is not None, "Supply --build-receipt and --qa")
    build = s.check_qa(Path(build_receipt), Path(qa), internal_beta=True)
    s.require(build["bundle_id"] == PACKAGE and build["platform"] == "android"
              and Path(build["artifact"]).suffix == ".aab", "Only a signed Musia Android AAB is allowed")
    version_code(build["build_number"])
    sha256(build["artifact_sha256"])
    return build


def coordination(path, record):
    s.require(path is not None, "Fresh parent/UI --coordination-file is required")
    value = s.read_json(s.private_file(path))
    s.require(value.get("schema") == 1 and value.get("bundle_id") == PACKAGE
              and value.get("track") == TRACK
              and value.get("version_code") == record["version_code"]
              and value.get("artifact_sha256") == record["artifact_sha256"],
              "Parent/UI coordination identity mismatch")
    s.require(isinstance(value.get("parent_session"), str) and value["parent_session"].strip()
              and all(value.get(flag) is True for flag in COORDINATION_FLAGS),
              "Parent must confirm quiescent UI, no other edits/pending changes/review, and commit risk")
    try:
        checked = dt.datetime.fromisoformat(value["checked_at"].replace("Z", "+00:00"))
        age = (dt.datetime.now(dt.timezone.utc) - checked).total_seconds()
    except (KeyError, TypeError, ValueError, AttributeError):
        raise s.GuardError("Invalid parent/UI coordination timestamp") from None
    s.require(0 <= age <= 600, "Parent/UI coordination is stale or in the future")
    return value


def no_retries(session):
    # AuthorizedSession otherwise transparently replays even POST after a 401.
    s.require(hasattr(session, "_max_refresh_attempts"), "Unsupported Google session retry policy")
    session._max_refresh_attempts = 0
    from requests.adapters import HTTPAdapter
    session.mount("https://", HTTPAdapter(max_retries=0))
    session.trust_env = False


class PlayInternalAPI:
    """A closed request vocabulary; no arbitrary paths, tracks, or request bodies."""

    def __init__(self, session, path, record, handoff, *, readback=False):
        self.session, self.path, self.record = session, path, record
        self.handoff, self.readback = handoff, readback

    def persist(self):
        save(self.path, self.record)

    def request(self, action, *, edit=None, step=None, media=None):
        s.require(self.record.get("bundle_id") == PACKAGE and self.record.get("track") == TRACK,
                  "Operation outside Musia internal scope")
        s.require(action in {"create", "get", "tracks", "bundles", "upload", "update", "commit", "delete"},
                  "Unsupported Play action")
        if action != "create":
            edit = edit_id(edit)
            owned = {row.get("response", {}).get("id") for row in self.record["steps"].values()
                     if row.get("action") == "create" and row.get("state") == "accepted"}
            s.require(edit in owned, "Edit is not owned by this exact operation")
        s.require(not self.readback or action not in {"upload", "update", "commit"},
                  "Readback cannot release or upload")
        s.require(action != "delete" or (self.readback and edit != self.record.get("edit_id")),
                  "Only a fresh read edit can be deleted")
        s.require(action not in {"upload", "update", "commit"} or edit == self.record.get("edit_id"),
                  "Mutation must use the original exact edit")
        method, url, kwargs = "GET", BASE + "/edits/" + (edit or ""), {}
        if action == "create":
            method, url, kwargs = "POST", BASE + "/edits", {"json": {}}
        elif action in {"tracks", "bundles"}:
            url += "/" + action
        elif action == "upload":
            s.require(media is not None and getattr(media, "name", None) == self.record.get("snapshot"),
                      "Exact snapshot media is required")
            checksum = hashlib.sha256()
            media.seek(0)
            for chunk in iter(lambda: media.read(1024 * 1024), b""):
                checksum.update(chunk)
            media.seek(0)
            s.require(checksum.hexdigest() == self.record["artifact_sha256"], "Snapshot stream hash mismatch")
            method, url = "POST", UPLOAD_BASE + "/edits/" + edit + "/bundles?uploadType=media"
            kwargs = {"data": media, "headers": {"Content-Type": "application/octet-stream"}}
        elif action == "update":
            method, url = "PUT", url + "/tracks/internal"
            kwargs = {"json": target_track(self.record)}
        elif action == "commit":
            method, url = "POST", url + ":commit" + COMMIT_QUERY
        elif action == "delete":
            method = "DELETE"
        mutation = method != "GET"
        entry = None
        if mutation:
            if not self.readback:
                s.require(step == {"create": "create_edit", "upload": "upload_bundle",
                                  "update": "update_internal", "commit": "commit_edit"}.get(action),
                          "Execution steps have fixed one-shot identities")
            s.require(isinstance(step, str) and step and step not in self.record["steps"],
                      "Mutation already attempted; reconcile, never blindly retry")
            handoff = coordination(self.handoff, self.record)
            entry = {"action": action, "method": method, "url": url, "state": "intent",
                     "at": s.now(), "edit_id": edit, "coordination": handoff}
            if "json" in kwargs:
                entry["body"] = copy.deepcopy(kwargs["json"])
            if action == "upload":
                entry["artifact_sha256"] = self.record["artifact_sha256"]
            self.record["steps"][step] = entry
            self.persist()
        try:
            response = self.session.request(method, url, **kwargs, timeout=(10, 180 if action == "upload" else 45),
                                            allow_redirects=False)
            if action == "get" and response.status_code == 404:
                return None
            s.require(200 <= response.status_code < 300, "Provider did not accept the request")
            s.require(len(response.content) <= 8 * 1024 * 1024, "Provider response too large")
            value = response.json() if response.content else {}
            s.require(isinstance(value, dict) and "error" not in value, "Malformed provider response")
            if action in {"create", "get", "commit"}:
                edit_id(value.get("id"))
                s.require(action == "create" or value["id"] == edit, "Provider edit mismatch")
            if action == "upload":
                exact_bundle(value, self.record)
            if action == "update":
                exact_internal(value, self.record)
        except Exception:
            if entry is not None:
                entry["state"] = "unknown"
                self.record["state"] = "unknown"
                self.persist()
            raise s.GuardError("Provider outcome unknown/unconfirmed; use --readback, never retry execution") from None
        if entry is not None:
            entry.update(state="accepted", response=value, finished_at=s.now())
            self.persist()
        return value


def tracks_by_name(payload):
    s.require(isinstance(payload, dict) and isinstance(payload.get("tracks"), list)
              and not payload.get("nextPageToken"), "Incomplete tracks inventory")
    result = {}
    for row in payload["tracks"]:
        s.require(isinstance(row, dict) and isinstance(row.get("track"), str) and row["track"]
                  and row["track"] not in result, "Malformed/duplicate track")
        s.require(isinstance(row.get("releases", []), list), "Malformed track releases")
        for release in row.get("releases", []):
            s.require(isinstance(release, dict) and release.get("status") in {"completed", "inProgress", "halted"},
                      "Draft or unknown release state; parent must reconcile unrelated work")
            codes = release.get("versionCodes")
            s.require(isinstance(codes, list) and codes, "Release version codes missing")
            s.require(len({version_code(c) for c in codes}) == len(codes), "Duplicate version code")
        result[row["track"]] = row
    s.require(TRACK in result, "Internal track missing from complete inventory")
    return result


def bundle_rows(payload):
    s.require(isinstance(payload, dict) and isinstance(payload.get("bundles"), list)
              and not payload.get("nextPageToken"), "Incomplete bundle inventory")
    codes = set()
    for row in payload["bundles"]:
        s.require(isinstance(row, dict), "Malformed bundle")
        code = version_code(row.get("versionCode"))
        s.require(code not in codes, "Duplicate provider bundle")
        codes.add(code)
    return payload["bundles"]


def exact_bundle(bundle, record):
    s.require(version_code(bundle.get("versionCode")) == record["version_code"]
              and bundle.get("sha256") == record["artifact_sha256"], "Provider bundle version/hash mismatch")


def find_bundle(payload, record):
    matches = [b for b in bundle_rows(payload) if version_code(b["versionCode"]) == record["version_code"]]
    if matches:
        exact_bundle(matches[0], record)
    return bool(matches)


def target_track(record):
    return {"track": TRACK, "releases": [{"name": record["release_name"],
             "versionCodes": [record["version_code"]], "status": "completed"}]}


def exact_internal(track, record):
    wanted = target_track(record)
    s.require(track.get("track") == TRACK and len(track.get("releases", [])) == 1,
              "Internal release readback mismatch")
    release = track["releases"][0]
    s.require(all(release.get(k) == v for k, v in wanted["releases"][0].items())
              and set(release) <= {"name", "versionCodes", "status", "inAppUpdatePriority"}
              and release.get("inAppUpdatePriority", 0) == 0, "Internal release readback mismatch")


def preserve_noninternal(baseline, current):
    before, after = tracks_by_name(baseline), tracks_by_name(current)
    s.require({k: v for k, v in before.items() if k != TRACK} ==
              {k: v for k, v in after.items() if k != TRACK}, "Non-internal tracks changed; refusing commit/success")


def run(build_receipt=None, qa=None, *, execute=False, service_account_file=None, coordination_file=None):
    build = qualified(build_receipt, qa)
    code = version_code(build["build_number"])
    path = operation_path(code)
    record = {"schema": 1, "state": "planned", "bundle_id": PACKAGE, "track": TRACK,
              "version_code": code, "artifact_sha256": build["artifact_sha256"],
              "source_sha256": build["source_sha256"], "release_name": f"{build['version']} ({code})",
              "steps": {}, "readbacks": []}
    if not execute:
        return {**record, "operation": str(path), "network": False, "existing_operation": path.exists(),
                "required_for_execution": ["--execute", "--service-account-file", "--coordination-file"]}
    with s.lock("play-upload"):
        s.require(not path.exists(), "Execution already attempted; use --readback on the existing operation")
        for other in path.parent.glob("play-internal-api-*.json"):
            s.require(s.read_json(s.private_file(other)).get("state") == "verified",
                      "Another internal operation is unresolved; reconcile it first")
        s.require(not (path.parent / ("play-upload-" + build["artifact_sha256"] + ".json")).exists(),
                  "Console upload already attempted; reconcile with parent first")
        coordination(coordination_file, record)
        s.require(service_account_file is not None, "Supply --service-account-file")
        key = s.private_file(service_account_file)
        record["service_account_sha256"] = s.digest(key)
        frozen = s.snapshot_artifact(build)
        record.update(state="started", at=s.now(), snapshot=frozen["artifact"],
                      build_receipt_sha256=s.digest(build_receipt), qa_sha256=s.digest(qa))
        with GoogleVerifier({"service_account_file": str(key)}).session() as session:
            no_retries(session)
            api = PlayInternalAPI(session, path, record, coordination_file)
            api.persist()
            try:
                created = api.request("create", step="create_edit")
                record["edit_id"] = created["id"]
                api.persist()
                edit = record["edit_id"]
                baseline = api.request("tracks", edit=edit)
                record["baseline_tracks"] = baseline
                bundles = api.request("bundles", edit=edit)
                record["baseline_bundles"] = bundles
                api.persist()
                tracks = tracks_by_name(baseline)
                internal = tracks[TRACK].get("releases", [])
                s.require(len(internal) <= 1 and all(r["status"] == "completed" for r in internal),
                          "Internal track has unrelated pending/staged releases")
                codes = [version_code(b["versionCode"]) for b in bundle_rows(bundles)]
                codes += [version_code(c) for t in tracks.values() for r in t.get("releases", [])
                          for c in r["versionCodes"]]
                s.require(all(int(c) < int(code) for c in codes),
                          "Version already present or not newer; reconcile instead of uploading")
                recheck(build_receipt, qa, record)
                with Path(frozen["artifact"]).open("rb") as media:
                    api.request("upload", edit=edit, media=media, step="upload_bundle")
                s.require(find_bundle(api.request("bundles", edit=edit), record), "Uploaded bundle missing")
                s.require(tracks_by_name(api.request("tracks", edit=edit)) == tracks,
                          "Track baseline changed before update")
                api.request("update", edit=edit, step="update_internal")
                after = api.request("tracks", edit=edit)
                record["precommit_tracks"] = after
                api.persist()
                preserve_noninternal(baseline, after)
                exact_internal(tracks_by_name(after)[TRACK], record)
                s.require(find_bundle(api.request("bundles", edit=edit), record), "Bundle missing before commit")
                recheck(build_receipt, qa, record)
                api.request("commit", edit=edit, step="commit_edit")
                record["state"] = "committed_unverified"
                api.persist()
            except Exception:
                if record["state"] != "unknown":
                    record["state"] = "blocked"
                    api.persist()
                raise
    return {"state": record["state"], "operation": str(path), "edit_id": record["edit_id"],
            "version_code": code, "artifact_sha256": record["artifact_sha256"]}


def recheck(build_receipt, qa, record):
    build = qualified(build_receipt, qa)
    s.require(build["artifact_sha256"] == record["artifact_sha256"]
              and s.digest(record["snapshot"]) == record["artifact_sha256"]
              and s.digest(build_receipt) == record["build_receipt_sha256"]
              and s.digest(qa) == record["qa_sha256"], "Qualified input changed during execution")


def readback(operation, *, service_account_file, coordination_file):
    with s.lock("play-upload"):
        path = s.private_file(operation)
        record = s.read_json(path)
        s.require(record.get("schema") == 1 and record.get("bundle_id") == PACKAGE
                  and record.get("track") == TRACK and path == operation_path(record.get("version_code")),
                  "Not a canonical Musia internal operation")
        sha256(record.get("artifact_sha256"))
        coordination(coordination_file, record)
        key = s.private_file(service_account_file)
        s.require(s.digest(key) == record.get("service_account_sha256"), "Service account differs from original operation")
        creation = record["steps"].get("create_edit", {})
        s.require(creation.get("state") == "accepted",
                  "Original edit creation unknown; parent/provider reconciliation required")
        original = edit_id(creation.get("response", {}).get("id"))
        s.require(record.get("edit_id", original) == original, "Original edit identity mismatch")
        record["edit_id"] = original
        s.require("baseline_tracks" in record, "No complete baseline; parent reconciliation required")
        with GoogleVerifier({"service_account_file": str(key)}).session() as session:
            no_retries(session)
            api = PlayInternalAPI(session, path, record, coordination_file, readback=True)
            original_live = api.request("get", edit=original)
            observation = {"at": s.now(), "original_edit_id": original, "state": "started"}
            record["readbacks"].append(observation)
            index = len(record["readbacks"])
            record["state"] = "reconciling"
            api.persist()
            edit = original
            if original_live is None:
                s.require("commit_edit" in record["steps"],
                          "Original edit missing without commit intent; do not infer success or retry")
                # An unresolved read-edit insertion/deletion must not be repeated either.
                for old in record["readbacks"][:-1]:
                    s.require(not old.get("fresh_edit") or old.get("deleted") is True,
                              "Prior read edit unresolved; parent must reconcile it")
                observation["fresh_edit"] = True
                api.persist()
                edit = api.request("create", step=f"readback_{index}_create")["id"]
            observation["edit_id"] = edit
            api.persist()
            try:
                tracks = api.request("tracks", edit=edit)
                bundles = api.request("bundles", edit=edit)
                observation.update(tracks=tracks, bundles=bundles)
                api.persist()
                preserve_noninternal(record["baseline_tracks"], tracks)
                present = find_bundle(bundles, record)
                observation["exact_bundle_present"] = present
                if original_live is not None:
                    internal = tracks_by_name(tracks)[TRACK]
                    baseline_internal = tracks_by_name(record["baseline_tracks"])[TRACK]
                    if "update_internal" not in record["steps"]:
                        s.require(internal == baseline_internal, "Original internal track changed without update intent")
                    elif internal != baseline_internal:
                        exact_internal(internal, record)
                    observation["state"] = "open_edit_only_not_committed"
                else:
                    s.require(present, "Exact bundle absent in fresh provider readback; outcome unresolved")
                    exact_internal(tracks_by_name(tracks)[TRACK], record)
                    observation["state"] = "verified"
            except Exception:
                observation["state"] = "unresolved"
                record["state"] = "unresolved"
                raise
            finally:
                api.persist()
                if observation.get("fresh_edit"):
                    api.request("delete", edit=edit, step=f"readback_{index}_delete")
                    observation["deleted"] = True
                    api.persist()
            if observation["state"] == "verified":
                record["state"] = "verified"
            else:
                record["state"] = "unresolved"
            api.persist()
            return {"state": observation["state"], "operation": str(path), "edit_id": edit,
                    "version_code": record["version_code"], "exact_bundle_present": present,
                    "noninternal_preserved": True, "tester_availability": "not_verified"}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--build-receipt", type=Path)
    parser.add_argument("--qa", type=Path)
    parser.add_argument("--service-account-file", type=Path)
    parser.add_argument("--coordination-file", type=Path)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--execute", action="store_true")
    mode.add_argument("--readback", type=Path, metavar="OPERATION")
    args = parser.parse_args(argv)
    try:
        if args.readback:
            s.require(args.service_account_file is not None and not args.build_receipt and not args.qa,
                      "Readback needs the original operation and --service-account-file, not new build inputs")
            result = readback(args.readback, service_account_file=args.service_account_file,
                              coordination_file=args.coordination_file)
        else:
            result = run(args.build_receipt, args.qa, execute=args.execute,
                         service_account_file=args.service_account_file, coordination_file=args.coordination_file)
        print(json.dumps(result, indent=2))
        return 0
    except (s.GuardError, OSError, ValueError, KeyError, TypeError, ImportError) as error:
        # Third-party exceptions can contain private credential paths/provider bodies.
        print(str(error) if isinstance(error, s.GuardError) else "Local input/runtime invalid; no retry authorized",
              file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
