#!/usr/bin/env python3
"""Reusable Musai song generation, correction, review, and handoff workbench."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
PROJECTS_ROOT = ROOT / "data" / "creative_projects"
ACE_ROOT = ROOT / "third_party" / "ACE-Step-1.5"
ACE_PYTHON = ACE_ROOT / ".venv" / "bin" / "python"
ACE_CHECKPOINTS = ACE_ROOT / "checkpoints"


LANG_LABELS = {
    "en": ("English", "English", "Latn"),
    "zh": ("Chinese", "中文", "Hans"),
    "zh-Hans": ("Chinese", "中文", "Hans"),
    "ja": ("Japanese", "日本語", "Jpan"),
    "ko": ("Korean", "한국어", "Kore"),
}


DEFAULT_LYRICS = {
    "ja": """[Verse 1]
窓辺で小さなアヤちゃん
雨粒を星に変える
赤いしっぽ そっと揺れて
眠る街へ歌を投げた

[Pre-Chorus]
怖くないよ ここにいるよ
胸の鈴が夜を照らす

[Chorus]
きらり きらり アヤちゃん
雲のすきまを走って
ひとりじゃない 夢は消えない
光の雨で踊ろう
""",
    "en": """[Verse]
Rain on the window, light in the street
I keep your small song close to me

[Chorus]
Shine on, shine on, gentle heart
We are not alone in the dark
""",
}


def now_stamp() -> str:
    return datetime.now().strftime("%Y%m%d-%H%M%S")


def iso_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def slugify(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "-", value.strip().lower()).strip("-")
    return cleaned or "song"


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def read_text_arg(text: str | None, file_path: str | None) -> str:
    if file_path:
        return Path(file_path).expanduser().read_text(encoding="utf-8").strip()
    return (text or "").strip()


def write_json(path: Path, data: Any) -> None:
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def toml_string(value: str | Path) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def language_label(code: str) -> tuple[str, str, str]:
    return LANG_LABELS.get(code, (code, code, ""))


def build_caption(args: argparse.Namespace) -> str:
    parts = [
        args.style or "cinematic polished pop song",
        args.genre or "",
        args.mood or "",
        f"{args.voice_notes}.",
        f"Vocal language: {args.vocal_language}.",
        f"Sing the provided lyrics as one continuous song with connected phrases and no clipped final words.",
        f"{args.keyscale}, {args.bpm} BPM, {args.time_signature}/4.",
    ]
    if args.idea:
        parts.insert(0, f"Song idea: {args.idea}.")
    if args.character:
        parts.insert(1, f"Character theme: {args.character}.")
    return " ".join(part.strip() for part in parts if part and part.strip())


def render_ace_config(
    project_dir: Path,
    lyrics_path: Path,
    language: str,
    caption: str,
    duration: int,
    bpm: int,
    keyscale: str,
    time_signature: str,
    model: str,
    seed: int,
    output_name: str,
    inference_steps: int,
    guidance_scale: float,
) -> str:
    save_dir = project_dir / "ace_outputs" / output_name
    lines = [
        "# Generated by Musai song workbench.",
        f"project_root = {toml_string(ACE_ROOT)}",
        f"checkpoint_dir = {toml_string(ACE_CHECKPOINTS)}",
        f"save_dir = {toml_string(save_dir)}",
        f"config_path = {toml_string(model)}",
        'task_type = "text2music"',
        f"caption = {toml_string(caption)}",
        f"lyrics = {toml_string(lyrics_path)}",
        f"duration = {int(duration)}",
        f"bpm = {int(bpm)}",
        f"keyscale = {toml_string(keyscale)}",
        f"timesignature = {toml_string(time_signature)}",
        f"vocal_language = {toml_string(language)}",
        "thinking = false",
        "use_cot_lyrics = false",
        "use_cot_caption = false",
        f"inference_steps = {int(inference_steps)}",
        f"guidance_scale = {float(guidance_scale)}",
        "use_random_seed = false",
        f"seeds = [{int(seed)}]",
        "batch_size = 1",
        'audio_format = "wav"',
        "",
    ]
    return "\n".join(lines)


def render_prompt_md(spec: dict[str, Any]) -> str:
    return "\n".join(
        [
            f"# {spec['title']}",
            "",
            "## Intent",
            "",
            spec.get("idea", ""),
            "",
            "## Audio Direction",
            "",
            f"- Language: `{spec['vocal_language']}`",
            f"- Duration: `{spec['duration']}` seconds",
            f"- BPM: `{spec['bpm']}`",
            f"- Key: `{spec['keyscale']}`",
            f"- Style: {spec.get('style', '')}",
            f"- Genre: {spec.get('genre', '')}",
            f"- Mood: {spec.get('mood', '')}",
            f"- Voice: {spec.get('voice_notes', '')}",
            "",
            "## ACE-Step Caption",
            "",
            "```text",
            spec["caption"],
            "```",
            "",
            "## Lyrics",
            "",
            "```text",
            spec["lyrics"],
            "```",
            "",
            "## Safety",
            "",
            "- Original lyrics and prompt.",
            "- No real-person voice clone or singer impersonation requested.",
            "- Character references are used as fictional production direction.",
            "",
        ]
    )


def render_review_checklist(spec: dict[str, Any]) -> str:
    return "\n".join(
        [
            f"# Review Checklist - {spec['title']}",
            "",
            "Use this before accepting a generated song.",
            "",
            "## Listen",
            "",
            "- [ ] Vocal is clearly audible and sung, not spoken.",
            "- [ ] Language is intelligible enough for the intended audience.",
            "- [ ] Last words and phrase endings are not clipped.",
            "- [ ] Melody feels connected across lines, not stitched line by line.",
            "- [ ] Arrangement supports the character/story mood.",
            "- [ ] No unwanted real-person vocal imitation.",
            "",
            "## Check With Musai",
            "",
            "```bash",
            "./commands.sh review",
            "./commands.sh analyze",
            "```",
            "",
            "## Correct If Needed",
            "",
            "Use `musai song correct` when ASR overlap is low, timing feels wrong, or the vocal needs a new prompt pass.",
            "",
        ]
    )


def render_lalachan_handoff(spec: dict[str, Any], audio_path: str = "", cover_path: str = "") -> str:
    audio = audio_path or "PENDING_GENERATED_AUDIO"
    cover = cover_path or "optional cover/poster path"
    return "\n".join(
        [
            f"# LALACHAN Song-To-Video Handoff - {spec['title']}",
            "",
            "Use this when ../LALACHAN or Xiaoyunque/Seedance should make a video from a completed Musai song.",
            "",
            "## Core Assets",
            "",
            f"- Song audio: `{audio}`",
            f"- Cover/poster: `{cover}`",
            f"- Lyrics: `{spec['lyrics_path']}`",
            f"- Project: `{spec['project_dir']}`",
            "",
            "## Character And Mood",
            "",
            f"- Character: {spec.get('character') or 'original character'}",
            f"- Mood: {spec.get('mood', '')}",
            f"- Video style: {spec.get('video_style', 'warm cinematic musical short film')}",
            "",
            "## Video Generation Prompt Draft",
            "",
            "```text",
            "Use the provided song audio as the timing and emotional reference. Create a polished musical short film for the character. "
            "The video should follow the song structure: quiet opening, gentle build, expressive chorus, and warm ending. "
            "Keep the character consistent with the uploaded reference images. Do not create subtitles, lyrics, file names, or path text in the video. "
            "Make camera movement musical and timed to phrase changes. Use soft cinematic lighting, clean staging, and expressive but natural movement.",
            "```",
            "",
            "## Workflow",
            "",
            "1. Generate or choose the final song audio in Musai.",
            "2. Run `./commands.sh review` and listen before using the song as video reference.",
            "3. Copy or reference this handoff from ../LALACHAN.",
            "4. Upload LALACHAN character references and the song audio to the video tool.",
            "5. Generate video from the finished song, then merge final video/audio only if the tool output changes the soundtrack.",
            "",
            "## Lyrics",
            "",
            "```text",
            spec["lyrics"],
            "```",
            "",
        ]
    )


def render_commands(project_dir: Path, config_path: Path, spec: dict[str, Any]) -> str:
    language = spec["vocal_language"]
    project_dir = project_dir.resolve()
    config_path = config_path.resolve()
    lyrics_path = Path(spec["lyrics_path"]).resolve()
    session = f"musai-song-{slugify(spec['title'])[:32]}"
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            f"ROOT_DIR={toml_string(ROOT)}",
            f"PROJECT_DIR={toml_string(project_dir)}",
            f"CONFIG={toml_string(config_path)}",
            f"LYRICS={toml_string(lyrics_path)}",
            f"LANGUAGE={toml_string(language)}",
            'cd "$ROOT_DIR"',
            "",
            'latest_audio() { find "$PROJECT_DIR/ace_outputs" -type f -name "*.wav" 2>/dev/null | sort | tail -n 1; }',
            "",
            'case "${1:-help}" in',
            "  generate)",
            '    cd third_party/ACE-Step-1.5',
            '    .venv/bin/python cli.py -c "$CONFIG" --backend "${ACE_BACKEND:-vllm}"',
            "    ;;",
            "  generate-tmux)",
            f"    tmux new-session -d -s {session} \"cd {ROOT} && {project_dir / 'commands.sh'} generate; read -p done\"",
            "    ;;",
            "  review)",
            '    audio="$(latest_audio)"',
            '    if [[ -z "${audio:-}" ]]; then echo "No generated WAV found." >&2; exit 1; fi',
            '    PYTHONNOUSERSITE=1 conda run -n musai python scripts/musai_song_workbench.py review --project-dir "$PROJECT_DIR" --audio "$audio" --lyrics-file "$LYRICS" --language "$LANGUAGE" --run-analysis',
            "    ;;",
            "  analyze)",
            '    audio="$(latest_audio)"',
            '    if [[ -z "${audio:-}" ]]; then echo "No generated WAV found." >&2; exit 1; fi',
            '    PYTHONNOUSERSITE=1 conda run -n musai python scripts/run_pipeline.py "$audio" --run-name "$(basename "$PROJECT_DIR")-analysis" --max-duration 180 --asr-model small --language "$LANGUAGE" --demucs-device "${MUSAI_DEMUCS_DEVICE:-cuda}"',
            "    ;;",
            "  correct)",
            '    shift || true',
            '    PYTHONNOUSERSITE=1 conda run -n musai python scripts/musai_song_workbench.py correct --project-dir "$PROJECT_DIR" "$@"',
            "    ;;",
            "  handoff)",
            '    audio="$(latest_audio)"',
            '    PYTHONNOUSERSITE=1 conda run -n musai python scripts/musai_song_workbench.py handoff --project-dir "$PROJECT_DIR" ${audio:+--audio "$audio"}',
            "    ;;",
            "  show)",
            '    sed -n "1,240p" "$PROJECT_DIR/PROMPT.md"',
            "    ;;",
            "  help|*)",
            "    echo 'Usage: commands.sh generate|generate-tmux|review|analyze|correct|handoff|show'",
            "    ;;",
            "esac",
            "",
        ]
    )


def find_latest_audio(project_dir: Path) -> Path | None:
    files = sorted((project_dir / "ace_outputs").glob("**/*.wav"))
    return files[-1] if files else None


def cmd_init(args: argparse.Namespace) -> None:
    lyrics = read_text_arg(args.lyrics, args.lyrics_file)
    if not lyrics:
        lyrics = DEFAULT_LYRICS.get(args.vocal_language, DEFAULT_LYRICS["en"]).strip()
    project_dir = Path(args.output_dir).expanduser() if args.output_dir else PROJECTS_ROOT / f"{now_stamp()}-{slugify(args.title)}"
    project_dir = ensure_dir(project_dir).resolve()
    lyrics_dir = ensure_dir(project_dir / "lyrics")
    lang = args.vocal_language
    lyrics_path = lyrics_dir / f"{lang}.txt"
    lyrics_path.write_text(lyrics.strip() + "\n", encoding="utf-8")

    caption = build_caption(args)
    config_path = project_dir / f"ace_{lang}.toml"
    spec = {
        "schema": "musai.song.workbench.v1",
        "created_at": iso_now(),
        "title": args.title,
        "idea": args.idea or "",
        "character": args.character or "",
        "language": args.language,
        "vocal_language": lang,
        "duration": args.duration,
        "bpm": args.bpm,
        "keyscale": args.keyscale,
        "time_signature": args.time_signature,
        "style": args.style or "",
        "genre": args.genre or "",
        "mood": args.mood or "",
        "voice_notes": args.voice_notes or "",
        "video_style": args.video_style or "",
        "model": args.model,
        "seed": args.seed,
        "inference_steps": args.inference_steps,
        "guidance_scale": args.guidance_scale,
        "caption": caption,
        "lyrics": lyrics.strip(),
        "lyrics_path": str(lyrics_path),
        "project_dir": str(project_dir),
        "ace_config": str(config_path),
    }
    config_path.write_text(
        render_ace_config(
            project_dir=project_dir,
            lyrics_path=lyrics_path,
            language=lang,
            caption=caption,
            duration=args.duration,
            bpm=args.bpm,
            keyscale=args.keyscale,
            time_signature=args.time_signature,
            model=args.model,
            seed=args.seed,
            output_name=lang,
            inference_steps=args.inference_steps,
            guidance_scale=args.guidance_scale,
        ),
        encoding="utf-8",
    )
    write_json(project_dir / "song_spec.json", spec)
    (project_dir / "PROMPT.md").write_text(render_prompt_md(spec), encoding="utf-8")
    (project_dir / "REVIEW_CHECKLIST.md").write_text(render_review_checklist(spec), encoding="utf-8")
    (project_dir / "LALACHAN_HANDOFF.md").write_text(render_lalachan_handoff(spec), encoding="utf-8")
    commands = project_dir / "commands.sh"
    commands.write_text(render_commands(project_dir, config_path, spec), encoding="utf-8")
    commands.chmod(0o755)
    print(project_dir)
    print(f"Config: {config_path}")
    print(f"Commands: {commands}")


def run_subprocess(cmd: list[str], cwd: Path = ROOT) -> tuple[int, str]:
    proc = subprocess.run(cmd, cwd=cwd, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    return proc.returncode, proc.stdout


def cmd_review(args: argparse.Namespace) -> None:
    project_dir = Path(args.project_dir).expanduser().resolve()
    audio = Path(args.audio).expanduser().resolve()
    lyrics_file = Path(args.lyrics_file).expanduser().resolve() if args.lyrics_file else project_dir / "lyrics" / f"{args.language}.txt"
    review_dir = ensure_dir(project_dir / "reviews" / now_stamp())

    quality_cmd = [
        sys.executable,
        str(ROOT / "scripts" / "musai_quality_check.py"),
        str(audio),
        "--language",
        args.language,
        "--expected-lyrics-file",
        str(lyrics_file),
        "--output-dir",
        str(review_dir),
    ]
    if args.asr_model:
        quality_cmd.extend(["--asr-model", args.asr_model])
    quality_code, quality_log = run_subprocess(quality_cmd)

    analysis_dir = ""
    analysis_log = ""
    if args.run_analysis:
        run_name = f"{project_dir.name}-{review_dir.name}-analysis"
        analysis_cmd = [
            sys.executable,
            str(ROOT / "scripts" / "run_pipeline.py"),
            str(audio),
            "--run-name",
            run_name,
            "--max-duration",
            str(args.max_duration),
            "--asr-model",
            args.asr_model or "small",
            "--language",
            args.language,
            "--demucs-device",
            args.demucs_device,
        ]
        analysis_code, analysis_log = run_subprocess(analysis_cmd)
        if analysis_code == 0:
            analysis_dir = str(ROOT / "data" / "runs" / run_name)

    quality = {}
    quality_path = review_dir / "quality.json"
    if quality_path.exists():
        quality = json.loads(quality_path.read_text(encoding="utf-8"))

    notes = []
    gate = quality.get("quality_gate", "unknown")
    if gate != "pass":
        notes.append("Automated quality gate is not pass; use `commands.sh correct` for a new prompt/seed pass.")
    if quality.get("lyric_overlap") is not None and quality.get("lyric_overlap", 0) < 0.55:
        notes.append("Lyric overlap is low. Shorten or simplify lyrics, raise vocal clarity in caption, or regenerate with a new seed.")
    if quality.get("rms", 0) < 0.02:
        notes.append("RMS is low. Consider a stronger vocal-forward prompt or post-mix loudness correction.")
    if not notes:
        notes.append("Automated checks are acceptable; still do a human listening pass for melody, phrasing, and emotional quality.")

    report = [
        f"# Song Review - {project_dir.name}",
        "",
        f"- Audio: `{audio}`",
        f"- Lyrics: `{lyrics_file}`",
        f"- Language: `{args.language}`",
        f"- Quality gate: `{gate}`",
        f"- ASR text: `{quality.get('asr_text', '')}`",
        f"- Lyric overlap: `{quality.get('lyric_overlap')}`",
        f"- RMS / peak: `{quality.get('rms')}` / `{quality.get('peak')}`",
        f"- Analysis dir: `{analysis_dir or 'not run'}`",
        "",
        "## Review Notes",
        "",
        *[f"- {note}" for note in notes],
        "",
        "## Quality Command Log",
        "",
        "```text",
        quality_log[-4000:],
        "```",
    ]
    if analysis_log:
        report += ["", "## Analysis Command Log", "", "```text", analysis_log[-4000:], "```"]
    (review_dir / "SONG_REVIEW.md").write_text("\n".join(report) + "\n", encoding="utf-8")
    print(review_dir / "SONG_REVIEW.md")


def cmd_correct(args: argparse.Namespace) -> None:
    project_dir = Path(args.project_dir).expanduser().resolve()
    spec_path = project_dir / "song_spec.json"
    if not spec_path.exists():
        raise SystemExit(f"Missing {spec_path}")
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    stamp = now_stamp()
    correction_dir = ensure_dir(project_dir / "corrections" / stamp)
    lyrics = read_text_arg(args.lyrics, args.lyrics_file) or spec["lyrics"]
    lyrics_path = correction_dir / f"{spec['vocal_language']}.txt"
    lyrics_path.write_text(lyrics.strip() + "\n", encoding="utf-8")
    seed = args.seed if args.seed is not None else int(spec.get("seed", 1000)) + 17
    caption = spec["caption"]
    if args.issues:
        caption += f" Correction notes: {args.issues}."
    if args.caption_extra:
        caption += " " + args.caption_extra.strip()
    config_path = correction_dir / f"ace_{spec['vocal_language']}_corrected.toml"
    config_path.write_text(
        render_ace_config(
            project_dir=project_dir,
            lyrics_path=lyrics_path,
            language=spec["vocal_language"],
            caption=caption,
            duration=int(args.duration or spec["duration"]),
            bpm=int(args.bpm or spec["bpm"]),
            keyscale=args.keyscale or spec["keyscale"],
            time_signature=str(spec.get("time_signature", "4")),
            model=args.model or spec["model"],
            seed=seed,
            output_name=f"{spec['vocal_language']}_corrected_{stamp}",
            inference_steps=int(args.inference_steps or spec.get("inference_steps", 8)),
            guidance_scale=float(args.guidance_scale or spec.get("guidance_scale", 1.0)),
        ),
        encoding="utf-8",
    )
    plan = [
        f"# Correction Plan - {spec['title']}",
        "",
        f"- Issues: {args.issues or 'manual correction pass'}",
        f"- Corrected config: `{config_path}`",
        f"- Corrected lyrics: `{lyrics_path}`",
        f"- Seed: `{seed}`",
        "",
        "Run:",
        "",
        "```bash",
        f"cd {ACE_ROOT} && .venv/bin/python cli.py -c {config_path} --backend vllm",
        "```",
        "",
    ]
    (correction_dir / "CORRECTION_PLAN.md").write_text("\n".join(plan), encoding="utf-8")
    print(correction_dir / "CORRECTION_PLAN.md")


def cmd_handoff(args: argparse.Namespace) -> None:
    project_dir = Path(args.project_dir).expanduser().resolve()
    spec = json.loads((project_dir / "song_spec.json").read_text(encoding="utf-8"))
    audio = args.audio or str(find_latest_audio(project_dir) or "")
    cover = args.cover or ""
    out = Path(args.output).expanduser() if args.output else project_dir / "LALACHAN_SONG_TO_VIDEO_HANDOFF.md"
    out.write_text(render_lalachan_handoff(spec, audio_path=audio, cover_path=cover), encoding="utf-8")
    print(out)


def cmd_find_audio(args: argparse.Namespace) -> None:
    audio = find_latest_audio(Path(args.project_dir).expanduser().resolve())
    if not audio:
        raise SystemExit("No generated WAV found.")
    print(audio)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    init = sub.add_parser("init", help="Create a reusable song generation project.")
    init.add_argument("--title", required=True)
    init.add_argument("--idea", default="")
    init.add_argument("--character", default="")
    init.add_argument("--lyrics")
    init.add_argument("--lyrics-file")
    init.add_argument("--language", default="ja")
    init.add_argument("--vocal-language", default="ja")
    init.add_argument("--duration", type=int, default=68)
    init.add_argument("--bpm", type=int, default=92)
    init.add_argument("--keyscale", default="G major")
    init.add_argument("--time-signature", default="4")
    init.add_argument("--style", default="")
    init.add_argument("--genre", default="")
    init.add_argument("--mood", default="")
    init.add_argument("--voice-notes", default="clear upfront young female vocal, expressive and natural")
    init.add_argument("--video-style", default="warm cinematic musical short film")
    init.add_argument("--model", default="acestep-v15-xl-turbo")
    init.add_argument("--seed", type=int, default=731001)
    init.add_argument("--inference-steps", type=int, default=10)
    init.add_argument("--guidance-scale", type=float, default=1.0)
    init.add_argument("--output-dir")
    init.set_defaults(func=cmd_init)

    review = sub.add_parser("review", help="Run QA and optional analysis on a generated song.")
    review.add_argument("--project-dir", required=True)
    review.add_argument("--audio", required=True)
    review.add_argument("--lyrics-file")
    review.add_argument("--language", default="ja")
    review.add_argument("--asr-model", default="small")
    review.add_argument("--run-analysis", action="store_true")
    review.add_argument("--max-duration", type=int, default=180)
    review.add_argument("--demucs-device", default="cuda")
    review.set_defaults(func=cmd_review)

    correct = sub.add_parser("correct", help="Create a corrected generation config from a review.")
    correct.add_argument("--project-dir", required=True)
    correct.add_argument("--issues", default="")
    correct.add_argument("--lyrics")
    correct.add_argument("--lyrics-file")
    correct.add_argument("--caption-extra", default="Make the vocal clearer, keep phrases connected, and avoid clipped line endings.")
    correct.add_argument("--seed", type=int)
    correct.add_argument("--duration", type=int)
    correct.add_argument("--bpm", type=int)
    correct.add_argument("--keyscale")
    correct.add_argument("--model")
    correct.add_argument("--inference-steps", type=int)
    correct.add_argument("--guidance-scale", type=float)
    correct.set_defaults(func=cmd_correct)

    handoff = sub.add_parser("handoff", help="Write or refresh a LALACHAN song-to-video handoff.")
    handoff.add_argument("--project-dir", required=True)
    handoff.add_argument("--audio")
    handoff.add_argument("--cover")
    handoff.add_argument("--output")
    handoff.set_defaults(func=cmd_handoff)

    find_audio = sub.add_parser("find-audio", help="Print newest generated WAV in a project.")
    find_audio.add_argument("--project-dir", required=True)
    find_audio.set_defaults(func=cmd_find_audio)

    return parser


def main() -> None:
    args = build_parser().parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
